version: '1.0'
services:
  mariadb:
    image: libp/mariadb:v1.2
    ports:
      - "3316:3306"
    environment:
      MARIADB_USER: root
      MARIADB_PASS: 111111
    volumes:
      - C:\Users\peng\docker\mysql:/var/lib/mysql


# An error occurred when using the following configuration 
# Error response from daemon: failed to mount local volume: 
# mount C:\Users\peng\docker\mysql:/var/lib/docker/volumes/mysql_db-data/_data, 
# flags: 0x1000: no such file or directory
  
    # volumes:
    #   - db-data:/var/lib/mysql

# volumes:
#   db-data:
#     driver: local
#     driver_opts:
#       type: "npipe"
#       o: "bind"
#       device: "C:\\Users\\peng\\docker\\mysql"
